# Generated by Django 6.0.1 on 2026-02-13 13:11

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app2', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
                ('meta', models.JSONField(default=dict)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(db_column='id', editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('active', models.BooleanField(default=True)),
                ('address', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee', to='app2.address')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee', to='app1.department')),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='EmployeeTags',
            fields=[
                ('id', models.BigAutoField(db_column='id', editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.employee')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.tags')),
            ],
            options={
                'db_table': 'employee_tag',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='tags',
            field=models.ManyToManyField(related_name='employees', through='app1.EmployeeTags', to='app2.tags'),
        ),
        migrations.AddIndex(
            model_name='employeetags',
            index=models.Index(fields=['employee', 'tag'], name='idx_employee_tag'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['name'], name='idx_employee_name'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['department'], name='idx_employee_department'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['address'], name='idx_employee_address'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['active'], name='idx_employee_active'),
        ),
    ]
